# Generated by Django 5.2.3 on 2025-09-19 16:40

import django.core.validators
import django.db.models.deletion
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("dashboard", "0003_currencyconversion_exchange_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ar_name", models.CharField(max_length=255)),
                ("en_name", models.CharField(max_length=255)),
                ("ar_value", models.CharField(max_length=255)),
                ("en_value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ar_name", models.CharField(max_length=255)),
                ("en_name", models.CharField(max_length=255)),
                ("ar_value", models.CharField(max_length=255)),
                ("en_value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StoreTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero1",
                    models.ImageField(blank=True, null=True, upload_to="stores/hero"),
                ),
                (
                    "hero2",
                    models.ImageField(blank=True, null=True, upload_to="stores/hero"),
                ),
                (
                    "hero3",
                    models.ImageField(blank=True, null=True, upload_to="stores/hero"),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="stores/logos"),
                ),
                ("cover", models.ImageField(upload_to="images/")),
                ("primary", models.CharField(max_length=10)),
                ("secondary", models.CharField(max_length=10)),
                ("tertiary", models.CharField(max_length=10)),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="stores/banners"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutoDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percent"),
                            ("fixed", "Fixed"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("percent", "Percent"),
                            ("fixed", "Fixed"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        max_length=100,
                    ),
                ),
                ("from_date", models.DateTimeField()),
                ("to_date", models.DateTimeField()),
                (
                    "stop_at",
                    models.CharField(
                        choices=[
                            ("500 sale", "Five Hundred Sale"),
                            ("200 sale", "Two Hundred Sale"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchantCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("parts", models.FloatField()),
                ("parts_name", models.CharField(max_length=10)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchantSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.CharField(blank=True, max_length=100, null=True)),
                ("twitter", models.CharField(blank=True, max_length=100, null=True)),
                ("instagram", models.CharField(blank=True, max_length=100, null=True)),
                ("telegram", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping", models.CharField(max_length=100)),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("paypal", "Paypal"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("bank_transfer", "Bank Transfer"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("total", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("feature1", models.CharField(blank=True, max_length=100, null=True)),
                ("feature2", models.CharField(blank=True, max_length=100, null=True)),
                ("feature3", models.CharField(blank=True, max_length=100, null=True)),
                ("feature4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("annual", "Annual"), ("monthly", "Monthly")],
                        default="monthly",
                        max_length=100,
                    ),
                ),
                (
                    "currnency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchantPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("expiresAt", models.DateTimeField()),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="merchant.plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/merchant/products"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/merchant/products"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/merchant/products"
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/merchant/products"
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/merchant/products"
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("en_name", models.CharField(max_length=100)),
                ("ar_name", models.CharField(blank=True, max_length=100, null=True)),
                ("barcode", models.CharField(blank=True, max_length=300, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("shipped", models.BooleanField(default=False)),
                ("tax", models.BooleanField(default=False)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("cost", models.FloatField(blank=True, null=True)),
                ("max_order_quantity", models.IntegerField(blank=True, null=True)),
                ("min_order_quantity", models.IntegerField(blank=True, null=True)),
                ("displayed", models.BooleanField(default=False)),
                ("price", models.FloatField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("current_quantity", models.IntegerField()),
                ("isActive", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=False)),
                (
                    "cost_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.merchantcurrency",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
                (
                    "weight_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.unit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerCartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.customercart",
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customercart",
            name="products",
            field=models.ManyToManyField(
                through="merchant.CustomerCartProduct", to="merchant.product"
            ),
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("en_name", models.CharField(max_length=100)),
                ("ar_name", models.CharField(max_length=100)),
                ("en_description", models.TextField(blank=True, null=True)),
                ("ar_description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/categories"
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="merchant.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="SaleCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("from_date", models.DateField(blank=True, null=True)),
                ("from_time", models.TimeField(blank=True, null=True)),
                ("purpose", models.CharField(max_length=100)),
                ("notify_through", models.CharField(max_length=100)),
                (
                    "client_selection",
                    models.CharField(
                        choices=[
                            ("ALL_CLIENTS", "All Clients"),
                            ("IMPORTED_CLIENTS", "Imported Clients"),
                            ("CLEINTS_PAST_30_DAYS", "Cleints Past 30 Days"),
                        ],
                        max_length=100,
                    ),
                ),
                ("campaign_timezone", models.CharField(max_length=100)),
                ("msg", models.TextField()),
                ("msg_time", models.TimeField(blank=True, null=True)),
                ("msg_date", models.DateField(blank=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ar_name", models.CharField(max_length=255)),
                ("en_name", models.CharField(max_length=255)),
                (
                    "percent",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("ar_description", models.TextField()),
                ("en_description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("TOTAL", "Total"),
                            ("DISCOUNT", "Discount"),
                            ("FREE", "Free"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("domain", models.CharField(default="test", max_length=100)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="merchant.storetheme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="theme/images/desktop")),
                ("mobile1", models.ImageField(upload_to="theme/images/mobile")),
                ("mobile2", models.ImageField(upload_to="theme/images/mobile")),
                ("mobile3", models.ImageField(upload_to="theme/images/mobile")),
                ("mobile4", models.ImageField(upload_to="theme/images/mobile")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("designer", models.CharField(max_length=100)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        default=utils.helper.generate_theme_slug,
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "currecny",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.currency",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="storetheme",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="merchant.theme"
            ),
        ),
        migrations.CreateModel(
            name="ThemeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="merchant.theme"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("selling_point", models.CharField(max_length=100)),
                ("long", models.CharField(max_length=100)),
                ("lat", models.CharField(max_length=100)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarehouseMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_warehouse",
                        to="merchant.warehouse",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.product",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_warehouse",
                        to="merchant.warehouse",
                    ),
                ),
            ],
        ),
    ]
