# Generated by Django 5.2.3 on 2025-07-15 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("rate", models.FloatField()),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchantSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.CharField(blank=True, max_length=100, null=True)),
                ("twitter", models.CharField(blank=True, max_length=100, null=True)),
                ("instagram", models.CharField(blank=True, max_length=100, null=True)),
                ("telegram", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("en_name", models.CharField(max_length=100)),
                ("ar_name", models.CharField(max_length=100)),
                ("en_description", models.TextField(blank=True, null=True)),
                ("ar_description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/categories"
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("en_name", models.CharField(max_length=100)),
                ("ar_name", models.CharField(blank=True, max_length=100, null=True)),
                ("barcode", models.CharField(blank=True, max_length=300, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("shipped", models.BooleanField(default=False)),
                ("tax", models.BooleanField(default=False)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("cost", models.FloatField(blank=True, null=True)),
                ("max_order_quantity", models.IntegerField(blank=True, null=True)),
                ("min_order_quantity", models.IntegerField(blank=True, null=True)),
                ("displayed", models.BooleanField(default=False)),
                ("price", models.FloatField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("current_quantity", models.IntegerField()),
                ("isActive", models.BooleanField(default=True)),
                ("isDeleted", models.BooleanField(default=False)),
                (
                    "cost_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.merchantcurrency",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
                (
                    "weight_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashboard.unit"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.productcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="stores/logos"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="stores/banners"
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=100)),
                ("selling_point", models.CharField(max_length=100)),
                ("long", models.CharField(max_length=100)),
                ("lat", models.CharField(max_length=100)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
    ]
