# Generated by Django 5.2.3 on 2025-07-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="merchantcurrency",
            old_name="rate",
            new_name="parts",
        ),
        migrations.AddField(
            model_name="merchantcurrency",
            name="parts_name",
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
