# Generated by Django 5.2.3 on 2025-07-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0002_rename_rate_merchantcurrency_parts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="link",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="name",
        ),
        migrations.AddField(
            model_name="productcategory",
            name="slug",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
