# Generated by Django 5.2.3 on 2025-08-05 17:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_currencyconversion_exchange_date"),
        ("merchant", "0004_warehousemove"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.ImageField(upload_to="theme/cover")),
                ("primary", models.CharField(max_length=10)),
                ("secondary", models.CharField(max_length=10)),
                ("tertiary", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="theme/images/desktop")),
                ("mobile1", models.ImageField(upload_to="theme/images/mobile")),
                ("mobile2", models.ImageField(upload_to="theme/images/mobile")),
                ("mobile3", models.ImageField(upload_to="theme/images/mobile")),
                ("mobile4", models.ImageField(upload_to="theme/images/mobile")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("designer", models.CharField(max_length=100)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "currecny",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThemeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="merchant.theme"
                    ),
                ),
            ],
        ),
    ]
