# Generated by Django 5.2.3 on 2025-08-08 14:34

import django.db.models.deletion
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merchant_business_type_merchant_share_location_and_more"),
        ("merchant", "0005_merchanttheme_theme_themereview"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerCartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.customercart",
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.ImageField(upload_to="images/")),
                ("primary", models.CharField(max_length=10)),
                ("secondary", models.CharField(max_length=10)),
                ("tertiary", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="MerchantTheme",
        ),
        migrations.AddField(
            model_name="theme",
            name="slug",
            field=models.CharField(
                default=utils.helper.generate_theme_slug, max_length=100, 
            ),
        ),
        migrations.AddField(
            model_name="customercart",
            name="products",
            field=models.ManyToManyField(
                through="merchant.CustomerCartProduct", to="merchant.product"
            ),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="merchant.theme"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="theme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="merchant.storetheme",
            ),
        ),
    ]
