# Generated by Django 5.2.3 on 2025-08-10 15:59

import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0006_customercart_customercartproduct_storetheme_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="store",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="storetheme",
            name="theme",
        ),
        migrations.AddField(
            model_name="storetheme",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="stores/banners"),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="stores/logos"),
        ),
        migrations.AlterField(
            model_name="theme",
            name="slug",
            field=models.CharField(
                default=utils.helper.generate_theme_slug, max_length=100, unique=True
            ),
        ),
    ]
