# Generated by Django 5.2.3 on 2025-08-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0007_remove_store_banner_remove_store_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storetheme",
            name="theme",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="merchant.theme",
            ),
            preserve_default=False,
        ),
    ]
