# Generated by Django 5.2.3 on 2025-08-10 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merchant_business_type_merchant_share_location_and_more"),
        ("merchant", "0008_storetheme_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="domain",
            field=models.CharField(default="test", max_length=100),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping", models.CharField(max_length=100)),
                (
                    "payment",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("credit_card", "Credit Card"),
                            ("paypal", "Paypal"),
                            ("apple_pay", "Apple Pay"),
                            ("google_pay", "Google Pay"),
                            ("bank_transfer", "Bank Transfer"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("total", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=100,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
            ],
        ),
    ]
