# Generated by Django 5.2.3 on 2025-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0009_store_domain_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/merchant/products"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/merchant/products"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/merchant/products"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/merchant/products"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image5",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/merchant/products"
            ),
        ),
    ]
