# Generated by Django 5.2.3 on 2025-08-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merchant_business_type_merchant_share_location_and_more"),
        ("dashboard", "0003_currencyconversion_exchange_date"),
        ("merchant", "0010_product_image1_product_image2_product_image3_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("feature1", models.CharField(blank=True, max_length=100, null=True)),
                ("feature2", models.CharField(blank=True, max_length=100, null=True)),
                ("feature3", models.CharField(blank=True, max_length=100, null=True)),
                ("feature4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("annual", "Annual"), ("monthly", "Monthly")],
                        default="monthly",
                        max_length=100,
                    ),
                ),
                (
                    "currnency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchantPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("expiresAt", models.DateTimeField()),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.merchant",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="merchant.plan"
                    ),
                ),
            ],
        ),
    ]
