# Generated by Django 5.2.3 on 2025-08-20 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0011_plan_merchantplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percent"),
                            ("fixed", "Fixed"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "percent",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("percent", "Percent"),
                            ("fixed", "Fixed"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        max_length=100,
                    ),
                ),
                ("from_date", models.DateTimeField()),
                ("to_date", models.DateTimeField()),
                (
                    "limit",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ar_name", models.CharField(max_length=255)),
                ("en_name", models.CharField(max_length=255)),
                ("ar_value", models.CharField(max_length=255)),
                ("en_value", models.CharField(max_length=255)),
            ],
        ),
    ]
