# Generated by Django 5.2.3 on 2025-09-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0012_autodiscount_productfilter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ar_name", models.CharField(max_length=255)),
                ("en_name", models.CharField(max_length=255)),
                ("ar_value", models.CharField(max_length=255)),
                ("en_value", models.CharField(max_length=255)),
            ],
        ),
    ]
