# Generated by Django 5.2.3 on 2025-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0013_productoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="storetheme",
            name="hero1",
            field=models.ImageField(blank=True, null=True, upload_to="stores/hero"),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="hero2",
            field=models.ImageField(blank=True, null=True, upload_to="stores/hero"),
        ),
        migrations.AddField(
            model_name="storetheme",
            name="hero3",
            field=models.ImageField(blank=True, null=True, upload_to="stores/hero"),
        ),
    ]
