# Generated by Django 5.2.3 on 2025-07-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currency",
            old_name="rate",
            new_name="parts",
        ),
        migrations.AddField(
            model_name="currency",
            name="parts_name",
            field=models.CharField(default=33, max_length=100),
            preserve_default=False,
        ),
    ]
