# Generated by Django 5.2.3 on 2025-07-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("fashion", "Fashion"),
                    ("electronics", "Electronics"),
                    ("food", "Food"),
                    ("books", "Books"),
                    ("home", "Home"),
                    ("beauty", "Beauty"),
                    ("sports", "Sports"),
                    ("toys", "Toys"),
                ],
                default="test",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="merchant",
            name="share_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="merchant",
            name="store_name",
            field=models.CharField(default="retail", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="merchant",
            name="store_type",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("wholesale", "Wholesale"),
                    ("manufacturing", "Manufacturing"),
                    ("services", "Services"),
                    ("digital", "Digital"),
                ],
                default="tst",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
