# Generated by Django 5.2.3 on 2025-09-08 16:13

import django.core.validators
import utils.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merchant_business_type_merchant_share_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="code",
            field=models.IntegerField(
                default=utils.helper.generate_code,
                validators=[
                    django.core.validators.MinValueValidator(100000),
                    django.core.validators.MaxValueValidator(999999),
                ],
            ),
        ),
    ]
