name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }} 
          debug: true  # Enable debug mode to get more information
          script: | 
            cd /home/store/Oia-Store 
            git add . 
            git stash
            git fetch origin
            git rebase origin
            docker-compose down
            docker-compose up -d --build 